FROM ebassi/flathub:base
MAINTAINER Emmanuele Bassi <ebassi@gmail.com>

ENV FLATPAK_OSTREE_REPO_MODE=user-only

RUN flatpak install gnome \ 
        org.gnome.Platform//3.24 \
        org.gnome.Sdk//3.24
